import { storage } from "./storage";

export async function populateSampleData() {
  try {
    // Check if data already exists
    const existingTrails = await storage.getTrails();
    if (existingTrails.length > 0) {
      console.log("Sample data already exists, skipping population");
      return;
    }

    console.log("Populating sample data...");

    // Sample Trails - Expanded with authentic Ubatuba trails
    const trails = [
      {
        name: "Trilha do Pico do Corcovado",
        description: "Uma das trilhas mais desafiadoras de Ubatuba, oferece vista panorâmica incrível da cidade e do oceano. Ideal para aventureiros experientes.",
        difficulty: "difícil",
        distance: "8.5",
        duration: 480,
        elevation: 1200,
        rating: "4.7",
        reviewCount: 156,
        imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha da Praia Brava",
        description: "Trilha de nível moderado que leva a uma das praias mais selvagens de Ubatuba. Perfeita para quem busca natureza preservada.",
        difficulty: "moderado",
        distance: "3.2",
        duration: 120,
        elevation: 200,
        rating: "4.3",
        reviewCount: 89,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha do Mirante da Barra Seca",
        description: "Trilha fácil e família-friendly com vista espetacular do pôr do sol. Ideal para iniciantes e crianças.",
        difficulty: "fácil",
        distance: "1.8",
        duration: 45,
        elevation: 150,
        rating: "4.5",
        reviewCount: 234,
        imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha da Cachoeira do Tobogã",
        description: "Trilha que leva a uma cachoeira natural com tobogã formado pelas rochas. Refreshante e divertida para toda família.",
        difficulty: "moderado",
        distance: "4.1",
        duration: 180,
        elevation: 300,
        rating: "4.6",
        reviewCount: 178,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha da Praia da Almada",
        description: "Trilha moderada através da Mata Atlântica até uma praia selvagem e praticamente deserta. Ideal para quem busca sossego.",
        difficulty: "moderado",
        distance: "2.8",
        duration: 90,
        elevation: 180,
        rating: "4.4",
        reviewCount: 67,
        imageUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha do Picinguaba",
        description: "Trilha costeira fácil que conecta várias praias da região norte. Passa por comunidade caiçara tradicional.",
        difficulty: "fácil",
        distance: "5.2",
        duration: 180,
        elevation: 50,
        rating: "4.2",
        reviewCount: 145,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha da Praia Vermelha do Norte",
        description: "Trilha de dificuldade moderada para uma das praias mais preservadas do litoral norte. Vista incrível do alto.",
        difficulty: "moderado",
        distance: "4.7",
        duration: 150,
        elevation: 320,
        rating: "4.8",
        reviewCount: 92,
        imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha da Ilha Anchieta",
        description: "Conjunto de trilhas na Ilha Anchieta, incluindo visita às ruínas do presídio e praias paradisíacas. Acesso por barco.",
        difficulty: "fácil",
        distance: "6.0",
        duration: 240,
        elevation: 100,
        rating: "4.9",
        reviewCount: 278,
        imageUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha do Núcleo Picinguaba",
        description: "Trilha interpretativa no Parque Estadual da Serra do Mar, com rica biodiversidade e cachoeiras cristalinas.",
        difficulty: "moderado",
        distance: "7.3",
        duration: 300,
        elevation: 450,
        rating: "4.6",
        reviewCount: 134,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        name: "Trilha da Fortaleza",
        description: "Trilha histórica até os canhões da época colonial com vista panorâmica da Baía de Ubatuba. Patrimônio histórico nacional.",
        difficulty: "fácil",
        distance: "1.2",
        duration: 30,
        elevation: 80,
        rating: "4.3",
        reviewCount: 189,
        imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      }
    ];

    // Sample Beaches - Expanded with authentic Ubatuba beaches
    const beaches = [
      {
        name: "Praia do Félix",
        description: "Uma das praias mais bonitas e preservadas de Ubatuba, ideal para quem busca tranquilidade e natureza exuberante.",
        features: ["estacionamento", "restaurantes", "trilhas"],
        activities: ["surf", "cenário", "trilha"],
        rating: "4.8",
        reviewCount: 312,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: true,
        isPreserved: true,
        accessType: "trilha",
      },
      {
        name: "Praia Grande",
        description: "A praia mais famosa e movimentada de Ubatuba, com excelente infraestrutura e opções de lazer para toda família.",
        features: ["estacionamento", "restaurantes", "salva-vidas", "chuveiros"],
        activities: ["surf", "vôlei", "caminhada"],
        rating: "4.2",
        reviewCount: 567,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: false,
        accessType: "carro",
      },
      {
        name: "Praia do Prumirim",
        description: "Praia paradisíaca cercada por mata atlântica, perfeita para mergulho e contemplação da natureza.",
        features: ["restaurantes", "trilhas"],
        activities: ["mergulho", "cenário", "pescaria"],
        rating: "4.7",
        reviewCount: 198,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: true,
        isPreserved: true,
        accessType: "trilha",
      },
      {
        name: "Praia da Fazenda",
        description: "Praia extensa e selvagem, ideal para longas caminhadas. Uma das mais preservadas do litoral sul de Ubatuba.",
        features: ["trilhas"],
        activities: ["caminhada", "cenário", "pescaria"],
        rating: "4.6",
        reviewCount: 89,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: true,
        isPreserved: true,
        accessType: "trilha",
      },
      {
        name: "Praia do Lázaro",
        description: "Praia familiar com boa infraestrutura, mar calmo e areia clara. Perfeita para crianças e relaxamento.",
        features: ["estacionamento", "restaurantes", "salva-vidas", "chuveiros"],
        activities: ["banho", "vôlei", "stand up"],
        rating: "4.3",
        reviewCount: 234,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: false,
        accessType: "carro",
      },
      {
        name: "Praia Vermelha do Norte",
        description: "Praia isolada e selvagem, accessible apenas por trilha. Mar cristalino e areia avermelhada única.",
        features: ["trilhas"],
        activities: ["mergulho", "cenário", "nudismo"],
        rating: "4.9",
        reviewCount: 156,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: true,
        isPreserved: true,
        accessType: "trilha",
      },
      {
        name: "Praia do Cedro",
        description: "Praia pequena e acolhedora no centro da cidade, com restaurantes e vida noturna próximos.",
        features: ["restaurantes", "bares", "estacionamento"],
        activities: ["banho", "stand up", "caiaque"],
        rating: "3.9",
        reviewCount: 178,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: false,
        accessType: "carro",
      },
      {
        name: "Praia da Almada",
        description: "Praia selvagem e deserta, accessible por trilha moderada. Ideal para quem busca isolamento total.",
        features: ["trilhas"],
        activities: ["cenário", "pescaria", "contemplação"],
        rating: "4.7",
        reviewCount: 92,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: true,
        isPreserved: true,
        accessType: "trilha",
      },
      {
        name: "Praia do Tenório",
        description: "Praia urbana com boa infraestrutura, próxima ao centro. Mar calmo ideal para famílias com crianças pequenas.",
        features: ["estacionamento", "restaurantes", "chuveiros", "playground"],
        activities: ["banho", "vôlei", "futebol"],
        rating: "4.1",
        reviewCount: 298,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: false,
        accessType: "carro",
      },
      {
        name: "Praia do Itaguá",
        description: "Praia extensa no centro da cidade com excelente infraestrutura turística e vida noturna agitada.",
        features: ["estacionamento", "restaurantes", "bares", "salva-vidas", "chuveiros"],
        activities: ["surf", "vôlei", "futebol", "caminhada"],
        rating: "4.0",
        reviewCount: 445,
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: false,
        accessType: "carro",
      },
      {
        name: "Praia do Flamengo",
        description: "Praia pequena e charmosa, protegida por morros. Mar calmo e cristalino, ideal para mergulho livre.",
        features: ["restaurantes", "estacionamento"],
        activities: ["mergulho", "stand up", "caiaque"],
        rating: "4.5",
        reviewCount: 167,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: false,
        accessType: "carro",
      },
      {
        name: "Praia de Picinguaba",
        description: "Praia em comunidade caiçara tradicional, com cultura local preservada e natureza exuberante.",
        features: ["restaurantes", "pousadas"],
        activities: ["cultura", "pescaria", "cenário"],
        rating: "4.4",
        reviewCount: 123,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isTopRated: false,
        isPreserved: true,
        accessType: "carro",
      }
    ];

    // Sample Boat Tours - Expanded with authentic Ubatuba boat tours
    const boatTours = [
      {
        name: "Passeio às Ilhas Anchieta e Comprida",
        description: "Tour completo pelas ilhas mais famosas da região, com paradas para mergulho e contemplação da vida marinha.",
        duration: 8,
        maxPeople: 12,
        price: "280.00",
        companyName: "Ubatuba Mar",
        rating: "4.6",
        reviewCount: 234,
        includes: ["equipamento", "almoço", "guia", "seguro"],
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: true,
        isRomantic: false,
      },
      {
        name: "Pôr do Sol Romântico",
        description: "Passeio especial para casais ao final da tarde, com drinks e vista espetacular do pôr do sol no mar.",
        duration: 3,
        maxPeople: 8,
        price: "180.00",
        companyName: "Romance no Mar",
        rating: "4.8",
        reviewCount: 89,
        includes: ["drinks", "petiscos", "música"],
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: false,
        isRomantic: true,
      },
      {
        name: "Passeio Ecológico às 7 Praias",
        description: "Tour pela costa sul visitando as praias mais preservadas com explicações sobre fauna e flora local.",
        duration: 6,
        maxPeople: 15,
        price: "220.00",
        companyName: "EcoTour Ubatuba",
        rating: "4.7",
        reviewCount: 178,
        includes: ["guia", "lanche", "equipamento", "seguro"],
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: true,
        isRomantic: false,
      },
      {
        name: "Pescaria Tradicional Caiçara",
        description: "Experiência autêntica de pesca com pescadores locais, inclui preparo do peixe e almoço na praia.",
        duration: 5,
        maxPeople: 8,
        price: "260.00",
        companyName: "Pescaria Caiçara",
        rating: "4.5",
        reviewCount: 134,
        includes: ["equipamento", "isca", "almoço", "bebida"],
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: true,
        isRomantic: false,
      },
      {
        name: "Mergulho na Ilha das Couves",
        description: "Mergulho livre ou com cilindro nas águas cristalinas da Ilha das Couves, com instrutor credenciado.",
        duration: 4,
        maxPeople: 10,
        price: "320.00",
        companyName: "Mergulho Ubatuba",
        rating: "4.9",
        reviewCount: 245,
        includes: ["equipamento", "instrutor", "lanche", "seguro"],
        imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: true,
        isRomantic: false,
      },
      {
        name: "Tour Gastronômico Marinho",
        description: "Passeio com degustação de frutos do mar frescos e visita a restaurantes flutuantes tradicionais.",
        duration: 5,
        maxPeople: 12,
        price: "350.00",
        companyName: "Sabores do Mar",
        rating: "4.6",
        reviewCount: 167,
        includes: ["degustação", "bebida", "guia", "transporte"],
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: false,
        isRomantic: true,
      },
      {
        name: "Passeio Noturno com Plâncton",
        description: "Experiência única navegando à noite para observar o fenômeno da bioluminescência do plâncton.",
        duration: 3,
        maxPeople: 6,
        price: "240.00",
        companyName: "Noite no Mar",
        rating: "4.8",
        reviewCount: 92,
        includes: ["lanterna", "colete", "guia", "lanche"],
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: false,
        isRomantic: true,
      },
      {
        name: "Circuito Aventura Aquática",
        description: "Passeio para esportistas com snorkeling, stand up paddle e caiaque nas melhores praias.",
        duration: 7,
        maxPeople: 10,
        price: "380.00",
        companyName: "Aventura Aquática",
        rating: "4.7",
        reviewCount: 156,
        includes: ["equipamentos", "instrutor", "almoço", "seguro"],
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
        isPopular: true,
        isRomantic: false,
      }
    ];

    // Sample Events - New authentic Ubatuba events
    const events = [
      {
        title: "Festival de Inverno de Ubatuba",
        description: "Festival cultural com shows nacionais, teatro, cinema e gastronomia típica durante todo o mês de julho.",
        startDate: new Date("2025-07-15"),
        endDate: new Date("2025-07-31"),
        startTime: "10:00",
        endTime: "22:00",
        location: "Centro Histórico de Ubatuba",
        ticketPrice: "0.00", // Free event
        category: "festival",
        producerId: "local-test-user",
        producerName: "Prefeitura de Ubatuba",
        imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        title: "Feira de Artesanato Caiçara",
        description: "Feira mensal com artesanato local, produtos da pesca tradicional e apresentações culturais caiçaras.",
        startDate: new Date("2025-08-10"),
        endDate: new Date("2025-08-10"),
        startTime: "08:00",
        endTime: "17:00",
        location: "Praça Exaltação da Santa Cruz",
        ticketPrice: "0.00",
        category: "cultura",
        producerId: "local-test-user",
        producerName: "Associação Artesãos Ubatuba",
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        title: "Regata de Canoas Caiçaras",
        description: "Competição tradicional de canoas caiçaras com participação das comunidades locais e premiação cultural.",
        startDate: new Date("2025-09-20"),
        endDate: new Date("2025-09-22"),
        startTime: "07:00",
        endTime: "18:00",
        location: "Praia do Perequê-Açu",
        ticketPrice: "15.00",
        category: "esporte",
        producerId: "local-test-user",
        producerName: "Comunidade Caiçara",
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        title: "Festival Gastronômico do Camarão",
        description: "Celebração da culinária local com pratos especiais de camarão preparados pelos melhores restaurantes da cidade.",
        startDate: new Date("2025-10-05"),
        endDate: new Date("2025-10-15"),
        startTime: "12:00",
        endTime: "23:00",
        location: "Diversos restaurantes",
        ticketPrice: "0.00",
        category: "gastronomia",
        producerId: "local-test-user",
        producerName: "AHRUB - Associação Hotéis e Restaurantes",
        imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        title: "Trilha Noturna na Mata Atlântica",
        description: "Caminhada noturna guiada para observação de fauna e flora nativas com guias especializados.",
        startDate: new Date("2025-08-25"),
        endDate: new Date("2025-08-25"),
        startTime: "19:00",
        endTime: "22:00",
        location: "Núcleo Picinguaba",
        ticketPrice: "45.00",
        category: "ecoturismo",
        producerId: "local-test-user",
        producerName: "EcoTurismo Ubatuba",
        imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      },
      {
        title: "Workshop de Fotografia de Natureza",
        description: "Curso intensivo de fotografia em cenários naturais de Ubatuba com fotógrafo profissional.",
        startDate: new Date("2025-09-14"),
        endDate: new Date("2025-09-15"),
        startTime: "06:00",
        endTime: "18:00",
        location: "Praia do Félix",
        ticketPrice: "280.00",
        category: "workshop",
        producerId: "local-test-user",
        producerName: "Escola de Fotografia Ubatuba",
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      }
    ];

    // Sample Guides - New authentic local guides
    const guides = [
      {
        userId: "local-test-user",
        name: "Carlos Oliveira",
        description: "Guia especializado em trilhas e ecoturismo com 15 anos de experiência. Conhece todas as trilhas da região e histórias locais.",
        specialties: ["trilhas", "ecoturismo", "história", "fotografia"],
        languages: ["português", "inglês"],
        experienceYears: 15,
        toursCompleted: 1250,
        rating: "4.9",
        imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        location: "Ubatuba, SP",
        certifications: ["Condutor Ambiental", "Primeiros Socorros", "Inglês Turístico"],
        whatsapp: "+55 12 99999-0001",
        instagram: "@carlosguiaubatuba",
      },
      {
        userId: "local-test-user",
        name: "Ana Santos",
        description: "Guia de mergulho credenciada e bióloga marinha. Especialista em vida aquática e conservação dos oceanos.",
        specialties: ["mergulho", "biologia marinha", "snorkeling", "conservação"],
        languages: ["português", "inglês", "espanhol"],
        experienceYears: 8,
        toursCompleted: 680,
        rating: "4.8",
        imageUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        location: "Ubatuba, SP",
        certifications: ["PADI Open Water", "Rescue Diver", "Biologia Marinha"],
        whatsapp: "+55 12 99999-0002",
        instagram: "@anamergulho",
      },
      {
        userId: "local-test-user",
        name: "João Pescador",
        description: "Pescador caiçara de terceira geração. Oferece experiências autênticas de pesca tradicional e cultura local.",
        specialties: ["pesca", "cultura caiçara", "culinária", "navegação"],
        languages: ["português"],
        experienceYears: 25,
        toursCompleted: 950,
        rating: "4.7",
        imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        location: "Picinguaba, Ubatuba",
        certifications: ["Mestre Pescador", "Cultura Caiçara Tradicional"],
        whatsapp: "+55 12 99999-0003",
        instagram: "@joaopescador",
      },
      {
        userId: "local-test-user",
        name: "Maria Costa",
        description: "Historiadora e guia cultural especializada no patrimônio histórico de Ubatuba e região. Tours educativos e culturais.",
        specialties: ["história", "patrimônio", "arquitetura", "cultura"],
        languages: ["português", "inglês", "francês"],
        experienceYears: 12,
        toursCompleted: 850,
        rating: "4.9",
        imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        location: "Centro Histórico, Ubatuba",
        certifications: ["História Regional", "Patrimônio Cultural", "Turismo Cultural"],
        whatsapp: "+55 12 99999-0004",
        instagram: "@mariahistoriaubatuba",
      },
      {
        userId: "local-test-user",
        name: "Pedro Aventura",
        description: "Instrutor de esportes aquáticos e guia de aventura. Especialista em stand up paddle, caiaque e trilhas aquáticas.",
        specialties: ["stand up", "caiaque", "surf", "aventura"],
        languages: ["português", "inglês"],
        experienceYears: 10,
        toursCompleted: 1100,
        rating: "4.8",
        imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        location: "Praia Grande, Ubatuba",
        certifications: ["Instrutor SUP", "Caiaque Oceânico", "Salvamento Aquático"],
        whatsapp: "+55 12 99999-0005",
        instagram: "@pedroaventura",
      },
      {
        userId: "local-test-user",
        name: "Fernanda Natureza",
        description: "Bióloga e educadora ambiental. Guia especializada em observação de aves e fauna da Mata Atlântica.",
        specialties: ["birdwatching", "fauna", "botânica", "educação ambiental"],
        languages: ["português", "inglês"],
        experienceYears: 7,
        toursCompleted: 520,
        rating: "4.9",
        imageUrl: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        location: "Núcleo Picinguaba, Ubatuba",
        certifications: ["Biologia Ambiental", "Educação Ambiental", "Observação de Aves"],
        whatsapp: "+55 12 99999-0006",
        instagram: "@fernandanatureza",
      }
    ];

    // Create sample data
    for (const trail of trails) {
      await storage.createTrail(trail);
    }

    for (const beach of beaches) {
      await storage.createBeach(beach);
    }

    for (const tour of boatTours) {
      await storage.createBoatTour(tour);
    }

    for (const event of events) {
      await storage.createEvent(event);
    }

    for (const guide of guides) {
      await storage.createGuide(guide);
    }

    console.log("Sample data populated successfully!");

  } catch (error) {
    console.error("Error populating sample data:", error);
  }
}